<a href="https://colab.research.google.com/github/muhmmadabuzar-svg/Dark-Pattern-Thesis/blob/main/04_visual_signal_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

input_file = "/content/drive/MyDrive/Dark Pattern Thesis/ocr_outputs/first_batch_keyword_detection_results.xlsx"

output_file = "/content/drive/MyDrive/Dark Pattern Thesis/ocr_outputs/first_batch_visual_signal_coding.xlsx"

df = pd.read_excel(input_file)

print("Total rows:", len(df))
df.head()

Total rows: 49

,image_id,filename,website,expected_category,ocr_text_raw,ocr_text_clean,ocr_status,character_count,word_count,preprocessing_method,tesseract_config,ocr_quality,notes,fake_urgency_matches,visual_misdirection_matches,obstruction_matches,fake_urgency_detected,visual_misdirection_detected,obstruction_detected,keyword_candidate_pattern
0,1,ALIEXPRESS_001_crop_free_gift_popup_obstructio...,ALIEXPRESS,candidate_obstruction,"mar iar CERES\n""raw yes. =\n= @\na a\ngift com...","mar iar CERES ""raw yes. = = @ a a gift coming ...",processed,161,39,grayscale_resize_200_otsu_threshold,--psm 6,Partial,"Free gift/returns text partly captured, but OC...",NaN,NaN,NaN,No,No,No,no_keyword_signal_detected
1,2,ALIEXPRESS_002_crop_early_bird_only_1_left_ocr...,ALIEXPRESS,candidate_fake_urgency,Lo ~ a\nwe ‘ . ae _\nid ed\n4 wr\na 7 y\ni¥@\n...,Lo ~ a we ‘ . ae _ id ed 4 wr a 7 y i¥@ e Choi...,processed,144,36,grayscale_resize_200_otsu_threshold,--psm 6,Good,"Urgency phrase “Early bird deal, only 1 left” ...","only, left, early bird","deal, off, % off",NaN,Yes,Yes,No,"candidate_fake_urgency, candidate_visual_misdi..."
2,3,ALIEXPRESS_003_crop_product_summer_savings_end...,ALIEXPRESS,candidate_fake_urgency,"-"" Sy UIU Allexpress app * EVR VY GY signin; K...","-"" Sy UIU Allexpress app * EVR VY GY signin; K...",processed,695,137,grayscale_resize_200_otsu_threshold,--psm 6,Good,Deal ending time and savings/ends signal captu...,"ends, deal ends, sold","deal, off, % off, save",welcome,Yes,Yes,Yes,"candidate_fake_urgency, candidate_visual_misdi..."
3,4,ALIEXPRESS_004_crop_product_bundle_deals_modal...,ALIEXPRESS,candidate_obstruction,portable wet and dry hair remover\n4.2 2185 Re...,portable wet and dry hair remover 4.2 2185 Rev...,processed,191,32,grayscale_resize_200_otsu_threshold,--psm 6,Good,Bundle deals and new shopper signal captured.,"only, sold",deal,NaN,Yes,Yes,No,"candidate_fake_urgency, candidate_visual_misdi..."
4,5,ALIEXPRESS_005_crop_product_superdeals_243_lef...,ALIEXPRESS,candidate_fake_urgency,os aay OO AliExpress app TT EURYV QQ Sign in /...,os aay OO AliExpress app TT EURYV QQ Sign in /...,processed,608,108,grayscale_resize_200_otsu_threshold,--psm 6,Good,“Only 234 left” and deal ending text captured.,"only, left, ends, sold","deal, superdeals",register,Yes,Yes,Yes,"candidate_fake_urgency, candidate_visual_misdi..."

In [ ]:
visual_columns = [
    # Fake urgency visual/textual visibility
    "countdown_timer_visible",
    "low_stock_text_visible",
    "limited_time_badge_visible",
    "urgency_text_visually_emphasized",

    # Visual misdirection
    "large_discount_banner",
    "large_sale_percentage",
    "crossed_out_price",
    "price_anchor_visible",
    "dominant_buy_button",
    "sale_color_emphasis",

    # Obstruction
    "popup_present",
    "popup_blocks_content",
    "dimmed_background",
    "small_close_button",
    "forced_signup_or_register",
    "app_download_prompt",

    # General coding notes
    "visual_coding_notes"
]

for col in visual_columns:
    if col not in df.columns:
        df[col] = ""

df.head()

,image_id,filename,website,expected_category,ocr_text_raw,ocr_text_clean,ocr_status,character_count,word_count,preprocessing_method,...,price_anchor_visible,dominant_buy_button,sale_color_emphasis,popup_present,popup_blocks_content,dimmed_background,small_close_button,forced_signup_or_register,app_download_prompt,visual_coding_notes
0,1,ALIEXPRESS_001_crop_free_gift_popup_obstructio...,ALIEXPRESS,candidate_obstruction,"mar iar CERES\n""raw yes. =\n= @\na a\ngift com...","mar iar CERES ""raw yes. = = @ a a gift coming ...",processed,161,39,grayscale_resize_200_otsu_threshold,...,,,,,,,,,,
1,2,ALIEXPRESS_002_crop_early_bird_only_1_left_ocr...,ALIEXPRESS,candidate_fake_urgency,Lo ~ a\nwe ‘ . ae _\nid ed\n4 wr\na 7 y\ni¥@\n...,Lo ~ a we ‘ . ae _ id ed 4 wr a 7 y i¥@ e Choi...,processed,144,36,grayscale_resize_200_otsu_threshold,...,,,,,,,,,,
2,3,ALIEXPRESS_003_crop_product_summer_savings_end...,ALIEXPRESS,candidate_fake_urgency,"-"" Sy UIU Allexpress app * EVR VY GY signin; K...","-"" Sy UIU Allexpress app * EVR VY GY signin; K...",processed,695,137,grayscale_resize_200_otsu_threshold,...,,,,,,,,,,
3,4,ALIEXPRESS_004_crop_product_bundle_deals_modal...,ALIEXPRESS,candidate_obstruction,portable wet and dry hair remover\n4.2 2185 Re...,portable wet and dry hair remover 4.2 2185 Rev...,processed,191,32,grayscale_resize_200_otsu_threshold,...,,,,,,,,,,
4,5,ALIEXPRESS_005_crop_product_superdeals_243_lef...,ALIEXPRESS,candidate_fake_urgency,os aay OO AliExpress app TT EURYV QQ Sign in /...,os aay OO AliExpress app TT EURYV QQ Sign in /...,processed,608,108,grayscale_resize_200_otsu_threshold,...,,,,,,,,,,

In [ ]:
df.to_excel(output_file, index=False)

print("Visual signal coding file created:")
print(output_file)

Visual signal coding file created:
/content/drive/MyDrive/Dark Pattern Thesis/ocr_outputs/first_batch_visual_signal_coding.xlsx

After running the above cell, a prompt will appear asking you to authorize Colab to access your Google Drive. Follow the instructions to complete the mounting process. Once mounted, you can rerun the cell that caused the error.